version: "3"
services:
#  db:
#    image: bitnami/postgresql
#    env_file:
#      - .env
#    environment:
#      - POSTGRES_USER=${DBUSER}
#      - POSTGRES_PASSWORD=${DBPASSWORD}
#      - POSTGRES_DB=${DBNAME}
#      - POSTGRES_HOST=${DBHOST}
#      - POSTGRES_PORT=${DBPORT}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - mynetwork


  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /root/FastAPI_Project/static/photo:/FastAPI_Project/static/photo/
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
