version: "3.9"

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_DB=${DBNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"

  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - celery_worker
    command: python3 app.py
    environment:
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}
      - DBNAME=${DBNAME}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_worker:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: celery -A service.celery_app worker --loglevel=info --uid=1000
    environment:
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}
      - DBNAME=${DBNAME}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_beat:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - celery_worker
    command: celery -A service.celery_app beat --loglevel=info --uid=1000
    environment:
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}
      - DBNAME=${DBNAME}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  postgres_data: