version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /root/FastAPI_Project/static/photo:/FastAPI_Project/static/photo/
    ports:
      - "8000:8000"
