version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /root/FastAPI_Project/static/photo:/FastAPI_Project/static/photo/
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  redis-cache:
    image: redis:alpine
    container_name: redis-cache_order
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
  cache:
