"""update executor profile table

Revision ID: 057d349af814
Revises: b5b68106bd35
Create Date: 2024-05-20 12:47:39.826336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057d349af814'
down_revision: Union[str, None] = 'b5b68106bd35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('icon_path', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('executor_profiles', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('executor_profiles', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('executor_profiles', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('executor_profiles', sa.Column('email', sa.String(), nullable=True))
    op.drop_constraint('executor_profiles_uuid_key', 'executor_profiles', type_='unique')
    op.drop_column('executor_profiles', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor_profiles', sa.Column('uuid', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('executor_profiles_uuid_key', 'executor_profiles', ['uuid'])
    op.drop_column('executor_profiles', 'email')
    op.drop_column('executor_profiles', 'phone_number')
    op.drop_column('executor_profiles', 'last_name')
    op.drop_column('executor_profiles', 'first_name')
    op.drop_table('tenant_notification')
    # ### end Alembic commands ###
