"""add balance pay to tenanT

Revision ID: 06acd5310de8
Revises: ff9089860964
Create Date: 2024-07-12 15:02:42.300416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06acd5310de8'
down_revision: Union[str, None] = 'ff9089860964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_profiles', sa.Column('pay_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_profiles', 'pay_balance')
    # ### end Alembic commands ###
