"""create new table Meter and MetersService

Revision ID: 13292b64985a
Revises: 6b44b45bf4c3
Create Date: 2024-04-05 16:25:29.981748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13292b64985a'
down_revision: Union[str, None] = '6b44b45bf4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meter_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('meter_service_id', sa.Integer(), nullable=True),
    sa.Column('bill_number', sa.String(), nullable=True),
    sa.Column('meters_for', sa.String(), nullable=True),
    sa.Column('meter_readings', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment_profiles.id'], ),
    sa.ForeignKeyConstraint(['meter_service_id'], ['meter_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meters')
    op.drop_table('meter_service')
    # ### end Alembic commands ###
