"""upgrade models9

Revision ID: 1fe567c9d78d
Revises: 9d29cc69e4d1
Create Date: 2024-02-22 17:22:15.927938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe567c9d78d'
down_revision: Union[str, None] = '9d29cc69e4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('order_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'documents', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'order_id')
    # ### end Alembic commands ###
