"""upgrade models7

Revision ID: 23466d0eab89
Revises: 69df330cbf4a
Create Date: 2024-02-22 15:51:36.453245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23466d0eab89'
down_revision: Union[str, None] = '69df330cbf4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additional_services', sa.Column('order_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'additional_services', 'orders', ['order_id'], ['id'])
    op.add_column('orders', sa.Column('tenant_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('status', sa.String(), nullable=False))
    op.create_foreign_key(None, 'orders', 'tenant_profiles', ['tenant_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'tenant_id')
    op.drop_constraint(None, 'additional_services', type_='foreignkey')
    op.drop_column('additional_services', 'order_id')
    # ### end Alembic commands ###
