"""add models NEWS new column photo path

Revision ID: 25a10719b7b4
Revises: c83eb3e1c2fa
Create Date: 2024-05-15 21:52:49.570505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a10719b7b4'
down_revision: Union[str, None] = 'c83eb3e1c2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('photo_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'photo_path')
    # ### end Alembic commands ###
