"""drop tables performer_profiles and invoice_history

Revision ID: 2673d5324201
Revises: f03d3e2689fd
Create Date: 2024-03-24 12:00:40.582420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2673d5324201'
down_revision: Union[str, None] = 'f03d3e2689fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
