"""update table additionla list service_list

Revision ID: 291b4884f0da
Revises: 36b28899752b
Create Date: 2024-03-30 17:07:18.459371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291b4884f0da'
down_revision: Union[str, None] = '36b28899752b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additional_services', sa.Column('additional_service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'additional_services', 'additional_services_list', ['additional_service_id'], ['id'])
    op.drop_column('additional_services', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additional_services', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'additional_services', type_='foreignkey')
    op.drop_column('additional_services', 'additional_service_id')
    # ### end Alembic commands ###
