"""add relationship UK payment object

Revision ID: 2a12ec367a9c
Revises: adea60f1de53
Create Date: 2024-02-22 03:48:21.327646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a12ec367a9c'
down_revision: Union[str, None] = 'adea60f1de53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
