"""delete address and add apartment_id to Order

Revision ID: 2d2ff968bb88
Revises: c3b6d185b1d0
Create Date: 2024-03-30 16:08:44.065378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2ff968bb88'
down_revision: Union[str, None] = 'c3b6d185b1d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('apartment_id', sa.Integer(), nullable=False))
    op.drop_column('orders', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'apartment_id')
    # ### end Alembic commands ###
