"""upgrade models16

Revision ID: 2fc852271b4c
Revises: bdfcbf03c3de
Create Date: 2024-02-22 20:20:04.876728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc852271b4c'
down_revision: Union[str, None] = 'bdfcbf03c3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additional_services', sa.Column('name', sa.VARCHAR(length=100), nullable=False))
    op.add_column('additional_services', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('additional_services', 'price')
    op.drop_column('additional_services', 'name')
    # ### end Alembic commands ###
