"""upgrade models

Revision ID: 33ee94425b63
Revises: 5d29e041f50c
Create Date: 2024-02-22 13:44:50.332134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ee94425b63'
down_revision: Union[str, None] = '5d29e041f50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additional_services', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'additional_services', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'additional_services', type_='foreignkey')
    op.drop_column('additional_services', 'item_id')
    # ### end Alembic commands ###
