"""upgrade models10

Revision ID: 3a31c1b7f7e1
Revises: 1fe567c9d78d
Create Date: 2024-02-22 17:25:01.319045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a31c1b7f7e1'
down_revision: Union[str, None] = '1fe567c9d78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('selected_service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'services', ['selected_service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'selected_service_id')
    # ### end Alembic commands ###
