"""add balance to tenant

Revision ID: 424b480700bb
Revises: 574360437614
Create Date: 2024-03-02 22:33:16.668778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424b480700bb'
down_revision: Union[str, None] = '574360437614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_profiles', sa.Column('balanse', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_profiles', 'balanse')
    # ### end Alembic commands ###
