"""add grade to order models

Revision ID: 430df37b5de6
Revises: c018109f62eb
Create Date: 2024-07-31 14:17:17.803928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430df37b5de6'
down_revision: Union[str, None] = 'c018109f62eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('grade', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'grade')
    # ### end Alembic commands ###
