"""remove column news_data and add create_at

Revision ID: 574360437614
Revises: 5cedcdb3b556
Create Date: 2024-03-02 20:01:40.191805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574360437614'
down_revision: Union[str, None] = '5cedcdb3b556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('created_at', sa.DATE(), nullable=True))
    op.drop_column('news', 'news_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('news_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('news', 'created_at')
    # ### end Alembic commands ###
