"""delete column tenant_id from apartmentProfile done

Revision ID: 5a58a3201252
Revises: bf4b7736240e
Create Date: 2024-05-19 15:20:06.882919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a58a3201252'
down_revision: Union[str, None] = 'bf4b7736240e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_tenant_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_tenant_id_fkey', 'orders', 'tenant_profiles', ['tenant_id'], ['id'])
    # ### end Alembic commands ###
