"""new table guest pass

Revision ID: 5a723c2eed49
Revises: affaacef3363
Create Date: 2024-04-21 20:58:14.076350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a723c2eed49'
down_revision: Union[str, None] = 'affaacef3363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_pass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.DATE(), nullable=True),
    sa.Column('visit_time', sa.TIME(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guest_pass_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('guest_pass_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guest_pass_id'], ['guest_pass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_pass_documents')
    op.drop_table('guest_pass')
    # ### end Alembic commands ###
