"""add table news foreig key

Revision ID: 5cedcdb3b556
Revises: cf713838533a
Create Date: 2024-03-02 19:07:05.268638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cedcdb3b556'
down_revision: Union[str, None] = 'cf713838533a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('object_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'news', 'object_profiles', ['object_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'object_id')
    # ### end Alembic commands ###
