"""delete order relationship

Revision ID: 5d29e041f50c
Revises: 6f4bbcd5d071
Create Date: 2024-02-22 13:26:43.582085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d29e041f50c'
down_revision: Union[str, None] = '6f4bbcd5d071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
