"""update table UK 

Revision ID: 5de9435ecfa9
Revises: dc24147e81ca
Create Date: 2024-03-23 12:30:21.400612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de9435ecfa9'
down_revision: Union[str, None] = 'dc24147e81ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uk_profiles', sa.Column('uuid', sa.String(), nullable=True))
    op.add_column('uk_profiles', sa.Column('photo_path', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'uk_profiles', ['uuid'])
    op.drop_column('uk_profiles', 'name')
    op.drop_column('uk_profiles', 'password')
    op.drop_column('uk_profiles', 'login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uk_profiles', sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('uk_profiles', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('uk_profiles', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'uk_profiles', type_='unique')
    op.drop_column('uk_profiles', 'photo_path')
    op.drop_column('uk_profiles', 'uuid')
    # ### end Alembic commands ###
