"""add active request for tenant

Revision ID: 685637c4cd75
Revises: bd154d684d47
Create Date: 2024-02-23 15:41:39.389515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685637c4cd75'
down_revision: Union[str, None] = 'bd154d684d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_profiles', sa.Column('active_request', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_profiles', 'active_request')
    # ### end Alembic commands ###
