"""create table BathroomApartment

Revision ID: 6b44b45bf4c3
Revises: 94852d2568d9
Create Date: 2024-03-31 19:32:08.088423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b44b45bf4c3'
down_revision: Union[str, None] = '94852d2568d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bathroom_apartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('characteristic', sa.String(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('apartment_profiles', 'bathrooms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment_profiles', sa.Column('bathrooms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('bathroom_apartments')
    # ### end Alembic commands ###
