"""testing new model

Revision ID: 6f4bbcd5d071
Revises: 063abef96973
Create Date: 2024-02-22 13:13:37.723898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4bbcd5d071'
down_revision: Union[str, None] = '063abef96973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('countable', sa.Boolean(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_additional_services_id'), 'additional_services', ['id'], unique=False)
    op.create_index(op.f('ix_additional_services_service'), 'additional_services', ['service'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('completion_date', sa.String(), nullable=True),
    sa.Column('completion_time', sa.String(), nullable=True),
    sa.Column('selected_services', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('item_additional_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('additional_service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['additional_service_id'], ['additional_services.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_additional_services_id'), 'item_additional_services', ['id'], unique=False)
    op.create_table('item_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_documents_id'), 'item_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_documents_id'), table_name='item_documents')
    op.drop_table('item_documents')
    op.drop_index(op.f('ix_item_additional_services_id'), table_name='item_additional_services')
    op.drop_table('item_additional_services')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_additional_services_service'), table_name='additional_services')
    op.drop_index(op.f('ix_additional_services_id'), table_name='additional_services')
    op.drop_table('additional_services')
    # ### end Alembic commands ###
