"""add table bank details and update table in executors

Revision ID: 78d23071df20
Revises: d32afdeabcf0
Create Date: 2024-03-24 12:02:43.465251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d23071df20'
down_revision: Union[str, None] = 'd32afdeabcf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_detail_executors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=False),
    sa.Column('purpose_of_payment', sa.String(), nullable=False),
    sa.Column('bic', sa.String(), nullable=False),
    sa.Column('correspondent_account', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('inn', sa.String(), nullable=False),
    sa.Column('kpp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('bank_details_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_details_id'], ['bank_detail_executors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('invoice_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('performer_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['object_profiles.id'], ),
    sa.ForeignKeyConstraint(['performer_id'], ['executor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_history')
    op.drop_table('executor_profiles')
    op.drop_table('bank_detail_executors')
    # ### end Alembic commands ###
