"""add new column is_view and type

Revision ID: 814aecc8d67e
Revises: cc461eebd5fe
Create Date: 2024-05-21 15:18:50.153468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '814aecc8d67e'
down_revision: Union[str, None] = 'cc461eebd5fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uk_notification', sa.Column('type', sa.String(), nullable=True))
    op.add_column('uk_notification', sa.Column('is_view', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uk_notification', 'is_view')
    op.drop_column('uk_notification', 'type')
    # ### end Alembic commands ###
