"""add new column to device token

Revision ID: 869ee1484940
Revises: e9ce33089f6d
Create Date: 2024-05-16 20:04:42.853281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '869ee1484940'
down_revision: Union[str, None] = 'e9ce33089f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executor_profiles', sa.Column('device_token', sa.String(), nullable=True))
    op.add_column('tenant_profiles', sa.Column('device_token', sa.String(), nullable=True))
    op.add_column('uk_employees', sa.Column('device_token', sa.String(), nullable=True))
    op.add_column('uk_profiles', sa.Column('device_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uk_profiles', 'device_token')
    op.drop_column('uk_employees', 'device_token')
    op.drop_column('tenant_profiles', 'device_token')
    op.drop_column('executor_profiles', 'device_token')
    # ### end Alembic commands ###
