"""added column created_at to Meters

Revision ID: 8a55b88115ab
Revises: ddba4b574c2d
Create Date: 2024-04-05 23:47:44.520405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a55b88115ab'
down_revision: Union[str, None] = 'ddba4b574c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meters', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meters', 'created_at')
    # ### end Alembic commands ###
