"""delete description for contacts

Revision ID: 8ace617b8708
Revises: 4c075d0dc5d5
Create Date: 2024-05-30 18:57:35.321113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ace617b8708'
down_revision: Union[str, None] = '4c075d0dc5d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('description', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
