"""add column object_id and relationship to EmpoleeUK

Revision ID: 8c029eeb0534
Revises: 76fd99718bf2
Create Date: 2024-03-09 19:03:58.305871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c029eeb0534'
down_revision: Union[str, None] = '76fd99718bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uk_employees', sa.Column('object_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'uk_employees', 'object_profiles', ['object_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uk_employees', type_='foreignkey')
    op.drop_column('uk_employees', 'object_id')
    # ### end Alembic commands ###
