"""added unique foreign key

Revision ID: 94852d2568d9
Revises: fa958c341b51
Create Date: 2024-03-31 16:54:18.512582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94852d2568d9'
down_revision: Union[str, None] = 'fa958c341b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'orders_executors', ['order_id'])
    op.create_unique_constraint(None, 'orders_executors', ['executor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders_executors', type_='unique')
    op.drop_constraint(None, 'orders_executors', type_='unique')
    # ### end Alembic commands ###
