"""upgrade models8

Revision ID: 9d29cc69e4d1
Revises: 23466d0eab89
Create Date: 2024-02-22 16:08:30.608126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d29cc69e4d1'
down_revision: Union[str, None] = '23466d0eab89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_selected_service_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'selected_service_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('selected_service_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_selected_service_id_fkey', 'orders', 'services', ['selected_service_id'], ['id'])
    # ### end Alembic commands ###
