"""add employee id for notifi

Revision ID: 9e5fa34b86b8
Revises: 75a88a7d04da
Create Date: 2024-05-29 17:34:22.163096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5fa34b86b8'
down_revision: Union[str, None] = '75a88a7d04da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_notification', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee_notification', 'uk_employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_notification', type_='foreignkey')
    op.drop_column('employee_notification', 'employee_id')
    # ### end Alembic commands ###
