"""update NotificationEmployee table 

Revision ID: a4e7c79fc9dd
Revises: 296d1a7791fe
Create Date: 2024-05-20 18:53:14.105077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e7c79fc9dd'
down_revision: Union[str, None] = '296d1a7791fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_notification', sa.Column('object_id', sa.Integer(), nullable=True))
    op.drop_constraint('employee_notification_employee_id_fkey', 'employee_notification', type_='foreignkey')
    op.create_foreign_key(None, 'employee_notification', 'uk_employees', ['object_id'], ['id'])
    op.drop_column('employee_notification', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_notification', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employee_notification', type_='foreignkey')
    op.create_foreign_key('employee_notification_employee_id_fkey', 'employee_notification', 'uk_employees', ['employee_id'], ['id'])
    op.drop_column('employee_notification', 'object_id')
    # ### end Alembic commands ###
