"""added column icons

Revision ID: affaacef3363
Revises: 8a55b88115ab
Create Date: 2024-04-07 19:52:30.301588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'affaacef3363'
down_revision: Union[str, None] = '8a55b88115ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meter_service', sa.Column('big_icons_path', sa.String(), nullable=True))
    op.add_column('meter_service', sa.Column('mini_icons_path', sa.String(), nullable=True))
    op.add_column('services', sa.Column('big_icons_path', sa.String(), nullable=True))
    op.add_column('services', sa.Column('mini_icons_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'mini_icons_path')
    op.drop_column('services', 'big_icons_path')
    op.drop_column('meter_service', 'mini_icons_path')
    op.drop_column('meter_service', 'big_icons_path')
    # ### end Alembic commands ###
