"""add table apartment profile tenant

Revision ID: b9778e769d53
Revises: ec8667a6b5df
Create Date: 2024-03-02 23:23:44.198705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9778e769d53'
down_revision: Union[str, None] = 'ec8667a6b5df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_apartments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('tenant_profiles_apartment_id_fkey', 'tenant_profiles', type_='foreignkey')
    op.drop_column('tenant_profiles', 'apartment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_profiles', sa.Column('apartment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tenant_profiles_apartment_id_fkey', 'tenant_profiles', 'apartment_profiles', ['apartment_id'], ['id'])
    op.drop_table('tenant_apartments')
    # ### end Alembic commands ###
