"""add two new column for notification

Revision ID: bc5e250d1dcd
Revises: f88288038555
Create Date: 2024-05-23 14:14:23.056404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5e250d1dcd'
down_revision: Union[str, None] = 'f88288038555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_notification', sa.Column('content_id', sa.Integer(), nullable=True))
    op.add_column('employee_notification', sa.Column('apartment_id', sa.Integer(), nullable=True))
    op.add_column('employee_notification', sa.Column('image', sa.String(), nullable=True))
    op.add_column('tenant_notification', sa.Column('content_id', sa.Integer(), nullable=True))
    op.add_column('tenant_notification', sa.Column('image', sa.String(), nullable=True))
    op.add_column('uk_notification', sa.Column('content_id', sa.Integer(), nullable=True))
    op.add_column('uk_notification', sa.Column('apartment_id', sa.Integer(), nullable=True))
    op.add_column('uk_notification', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uk_notification', 'image')
    op.drop_column('uk_notification', 'apartment_id')
    op.drop_column('uk_notification', 'content_id')
    op.drop_column('tenant_notification', 'image')
    op.drop_column('tenant_notification', 'content_id')
    op.drop_column('employee_notification', 'image')
    op.drop_column('employee_notification', 'apartment_id')
    op.drop_column('employee_notification', 'content_id')
    # ### end Alembic commands ###
