"""upgrade models14

Revision ID: bdfcbf03c3de
Revises: d1ccb62f83a6
Create Date: 2024-02-22 18:13:54.931227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdfcbf03c3de'
down_revision: Union[str, None] = 'd1ccb62f83a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'completion_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('orders', 'completion_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'completion_time',
               existing_type=sa.VARCHAR(length=20),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('orders', 'completion_date',
               existing_type=sa.VARCHAR(length=20),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
