"""add relationship UK payment object_appartament

Revision ID: bf137a75f43b
Revises: 2a12ec367a9c
Create Date: 2024-02-22 03:49:23.013266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf137a75f43b'
down_revision: Union[str, None] = '2a12ec367a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
