"""add apartment_id for tenant notifications

Revision ID: c018109f62eb
Revises: 06acd5310de8
Create Date: 2024-07-17 15:03:58.073342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c018109f62eb'
down_revision: Union[str, None] = '06acd5310de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_notification', sa.Column('apartment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tenant_notification', 'apartment_profiles', ['apartment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant_notification', type_='foreignkey')
    op.drop_column('tenant_notification', 'apartment_id')
    # ### end Alembic commands ###
