"""update table payment_details_uk

Revision ID: c3b6d185b1d0
Revises: 797cb40b14a8
Create Date: 2024-03-25 09:10:05.673170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b6d185b1d0'
down_revision: Union[str, None] = '797cb40b14a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_details_uk', sa.Column('okpo', sa.String(), nullable=False))
    op.drop_column('payment_details_uk', 'contact_number')
    op.drop_column('payment_details_uk', 'purpose_of_payment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_details_uk', sa.Column('purpose_of_payment', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('payment_details_uk', sa.Column('contact_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('payment_details_uk', 'okpo')
    # ### end Alembic commands ###
