"""add photo path to apartment

Revision ID: c7a7b1ba7713
Revises: f465452de644
Create Date: 2024-05-13 15:51:57.372014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a7b1ba7713'
down_revision: Union[str, None] = 'f465452de644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment_profiles', sa.Column('photo_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartment_profiles', 'photo_path')
    # ### end Alembic commands ###
