"""update table news remove object_id and add uk_id

Revision ID: c83eb3e1c2fa
Revises: f8bef22ccd54
Create Date: 2024-05-15 11:17:09.432900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83eb3e1c2fa'
down_revision: Union[str, None] = 'f8bef22ccd54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('uk_id', sa.Integer(), nullable=True))
    op.drop_constraint('news_object_id_fkey', 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'uk_profiles', ['uk_id'], ['id'])
    op.drop_column('news', 'object_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key('news_object_id_fkey', 'news', 'object_profiles', ['object_id'], ['id'])
    op.drop_column('news', 'uk_id')
    # ### end Alembic commands ###
