"""delete unique constarin from executorOrder

Revision ID: cc461eebd5fe
Revises: a4e7c79fc9dd
Create Date: 2024-05-20 20:24:15.110559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc461eebd5fe'
down_revision: Union[str, None] = 'a4e7c79fc9dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_executors_executor_id_key', 'orders_executors', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('orders_executors_executor_id_key', 'orders_executors', ['executor_id'])
    # ### end Alembic commands ###
