"""upgrade models13

Revision ID: d1ccb62f83a6
Revises: 88cc79a53b3c
Create Date: 2024-02-22 17:45:21.432959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ccb62f83a6'
down_revision: Union[str, None] = '88cc79a53b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'countable')
    op.drop_column('services', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('countable', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
