"""upgrade models3

Revision ID: da773fe8a7ba
Revises: 26931c23c9c6
Create Date: 2024-02-22 13:53:45.423022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da773fe8a7ba'
down_revision: Union[str, None] = '26931c23c9c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('additional_services_item_id_fkey', 'additional_services', type_='foreignkey')
    op.drop_column('additional_services', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additional_services', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('additional_services_item_id_fkey', 'additional_services', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
