"""added column to Employee is_admin

Revision ID: dc24147e81ca
Revises: e7e64eb1e29f
Create Date: 2024-03-23 11:12:30.629681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc24147e81ca'
down_revision: Union[str, None] = 'e7e64eb1e29f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uk_employees', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uk_employees', 'is_admin')
    # ### end Alembic commands ###
