"""update relationships order to apartments

Revision ID: dc8a4a76072f
Revises: 2d2ff968bb88
Create Date: 2024-03-30 16:12:00.652248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc8a4a76072f'
down_revision: Union[str, None] = '2d2ff968bb88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'apartment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'orders', 'apartment_profiles', ['apartment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'apartment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
