"""added column to Invoice History

Revision ID: ddba4b574c2d
Revises: f8103139c66a
Create Date: 2024-04-05 20:14:28.781784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddba4b574c2d'
down_revision: Union[str, None] = 'f8103139c66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_history', sa.Column('apartment_id', sa.Integer(), nullable=True))
    op.add_column('invoice_history', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('invoice_history', sa.Column('service_id', sa.Integer(), nullable=True))
    op.add_column('invoice_history', sa.Column('meter_service_id', sa.Integer(), nullable=True))
    op.add_column('invoice_history', sa.Column('bill_number', sa.String(), nullable=True))
    op.drop_constraint('invoice_history_performer_id_fkey', 'invoice_history', type_='foreignkey')
    op.drop_constraint('invoice_history_object_id_fkey', 'invoice_history', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_history', 'meter_service', ['meter_service_id'], ['id'])
    op.create_foreign_key(None, 'invoice_history', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'invoice_history', 'apartment_profiles', ['apartment_id'], ['id'])
    op.drop_column('invoice_history', 'performer_id')
    op.drop_column('invoice_history', 'object_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_history', sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('invoice_history', sa.Column('performer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoice_history', type_='foreignkey')
    op.drop_constraint(None, 'invoice_history', type_='foreignkey')
    op.drop_constraint(None, 'invoice_history', type_='foreignkey')
    op.create_foreign_key('invoice_history_object_id_fkey', 'invoice_history', 'object_profiles', ['object_id'], ['id'])
    op.create_foreign_key('invoice_history_performer_id_fkey', 'invoice_history', 'executor_profiles', ['performer_id'], ['id'])
    op.drop_column('invoice_history', 'bill_number')
    op.drop_column('invoice_history', 'meter_service_id')
    op.drop_column('invoice_history', 'service_id')
    op.drop_column('invoice_history', 'comment')
    op.drop_column('invoice_history', 'apartment_id')
    # ### end Alembic commands ###
