"""delete unique name from news

Revision ID: e9ce33089f6d
Revises: 08d08ee3c5a5
Create Date: 2024-05-16 18:32:28.619685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ce33089f6d'
down_revision: Union[str, None] = '08d08ee3c5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('news_name_key', 'news', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('news_name_key', 'news', ['name'])
    # ### end Alembic commands ###
