"""update balance to tenant

Revision ID: ec8667a6b5df
Revises: 424b480700bb
Create Date: 2024-03-02 22:54:00.200908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8667a6b5df'
down_revision: Union[str, None] = '424b480700bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_profiles', sa.Column('balance', sa.Float(), nullable=True))
    op.drop_column('tenant_profiles', 'balanse')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_profiles', sa.Column('balanse', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('tenant_profiles', 'balance')
    # ### end Alembic commands ###
