"""update table UK to add name

Revision ID: f03d3e2689fd
Revises: 5de9435ecfa9
Create Date: 2024-03-23 12:38:49.976718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03d3e2689fd'
down_revision: Union[str, None] = '5de9435ecfa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uk_profiles', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uk_profiles', 'name')
    # ### end Alembic commands ###
