"""added column status

Revision ID: f8103139c66a
Revises: 7b454473cd0e
Create Date: 2024-04-05 17:38:52.700743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8103139c66a'
down_revision: Union[str, None] = '7b454473cd0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meters', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meters', 'status')
    # ### end Alembic commands ###
