"""add column to order is_view

Revision ID: f8bef22ccd54
Revises: c7a7b1ba7713
Create Date: 2024-05-13 18:39:46.918022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8bef22ccd54'
down_revision: Union[str, None] = 'c7a7b1ba7713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_view', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_view')
    # ### end Alembic commands ###
