"""add column objects_name to Objects

Revision ID: fba1f29e3775
Revises: 92bfae700712
Create Date: 2024-03-09 15:01:54.021969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba1f29e3775'
down_revision: Union[str, None] = '92bfae700712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_profiles', sa.Column('object_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object_profiles', 'object_name')
    # ### end Alembic commands ###
