"""add foreign key to payment_details

Revision ID: fd56d78d4f26
Revises: f74e57f08672
Create Date: 2024-03-25 09:00:59.354063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd56d78d4f26'
down_revision: Union[str, None] = 'f74e57f08672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_details_uk', sa.Column('uk_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payment_details_uk', 'uk_profiles', ['uk_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_details_uk', type_='foreignkey')
    op.drop_column('payment_details_uk', 'uk_id')
    # ### end Alembic commands ###
