"""add new column is_view and type to employee and tenant

Revision ID: fd9666bd2d39
Revises: 814aecc8d67e
Create Date: 2024-05-21 15:21:48.501432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9666bd2d39'
down_revision: Union[str, None] = '814aecc8d67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_notification', sa.Column('type', sa.String(), nullable=True))
    op.add_column('employee_notification', sa.Column('is_view', sa.Boolean(), nullable=True))
    op.add_column('tenant_notification', sa.Column('type', sa.String(), nullable=True))
    op.add_column('tenant_notification', sa.Column('is_view', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_notification', 'is_view')
    op.drop_column('tenant_notification', 'type')
    op.drop_column('employee_notification', 'is_view')
    op.drop_column('employee_notification', 'type')
    # ### end Alembic commands ###
