"""add new column status ExecutorOrder

Revision ID: fe92487388ac
Revises: e4f15025b7b6
Create Date: 2024-05-20 15:21:42.482079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe92487388ac'
down_revision: Union[str, None] = 'e4f15025b7b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_executors', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_executors', 'status')
    # ### end Alembic commands ###
